/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as clock from "./clock";
export { GovernorToken__factory } from "./GovernorToken__factory";
export { OZGovernor__factory } from "./OZGovernor__factory";
export { TimelockController__factory } from "./TimelockController__factory";
