/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as clock from "./clock";
export type { clock };
export type { ERC20Token } from "./ERC20Token";
export type { OZGovernor } from "./OZGovernor";
export type { TimelockController } from "./TimelockController";
