/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernorToken__factory } from "./GovernorToken__factory";
export { OZGovernor__factory } from "./OZGovernor__factory";
